#!/bin/sh
#
# *****************************************************************************
# *
# * Copyright (C) 2012 Thomas Volkert <thomas@homer-conferencing.com>
# *
# * This software is free software.
# * Your are allowed to redistribute it and/or modify it under the terms of
# * the GNU General Public License version 2 as published by the Free Software
# * Foundation.
# *
# * This source is published in the hope that it will be useful, but
# * WITHOUT ANY WARRANTY or FITNESS FOR A PARTICULAR PURPOSE. See the
# * GNU General Public License version 2 for more details.
# *
# * You should have received a copy of the GNU General Public License version 2
# * along with this program. Otherwise, you can write to the Free Software
# * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02111, USA.
# * Alternatively, you find an online version of the license text under
# * http://www.gnu.org/licenses/gpl-2.0.html.
# *
# *****************************************************************************
#
#
# Purpose: start script for Homer Conferencing on OSX systems
# Author:  Thomas Volkert
# Since:   2012-08-20
#

# get the absolute path to this bundle
ABS_BUNDLE_PATH="`echo "$0" | sed -e 's/\/Contents\/MacOS\/Homer-Conferencing//'`"
ABS_BIN_PATH=${ABS_BUNDLE_PATH}/Contents/Resources
ABS_LIB_PATH=${ABS_BUNDLE_PATH}/Contents/Resources/lib

# set the LD library path
export "DYLD_LIBRARY_PATH=${ABS_LIB_PATH}"

# start Homer Conferencing main binary
exec "${ABS_BIN_PATH}/Homer"